version: "3.9"

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: lina-goapp:v1
    container_name: goapp
    environment:
    
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      ACTIVE_SESSIONS_CONDITION: "end_time IS NULL"
      TZ: ${TZ}
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - goapp
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
