version: "3.9"

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: lina-goapp:v1
    container_name: goapp
    environment:
      # Real DB connection (provided)
      DB_HOST: "migrate.cluster-c3o6qc26ias1.eu-west-1.rds.amazonaws.com"
      DB_PORT: "3306"
      DB_USER: "lina"
      DB_PASS: "123456"                        # <<< set DB password here if required
      DB_NAME: "ocpp_CSGO"

      # Active sessions condition (customize if needed)
      ACTIVE_SESSIONS_CONDITION: "end_time IS NULL"
      TZ: "UTC"
    ports:
      - "8000:8000"   # optional for direct debug
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - goapp
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

# Both services share the default compose network, so nginx can reach http://goapp:8000
